### ISSUE TITLE
FINAL NOTICE: Immediate Removal of SpringRacks from Summer Host List Required or Face Legal Action

### ISSUE THREAD

**Issue by LayTooPlant** [setupmd/docs#125]
### Declaration

- [X] I declare that I am authorised to speak on behalf of this business entity.
- [X] I declare that dishonestly completing this form will result in a permanent removal blacklist for the hosting entity.

### Hosting Provider Name

SpringRacks

### Evidence

Dear setup.md maintainers,

This communication serves as a **final notice** demanding the immediate removal of SpringRacks from your list of summer hosts. Your recent response has been noted, but it fails to address the gravity of the situation.

SpringRacks is not a summer host, and the incorrect listing on your platform is causing severe damage to our business reputation. This misidentification constitutes defamation and libel, which are criminal offenses under both Turkish and UK law. Under Article 125 of the Turkish Penal Code, defamation can lead to substantial fines and jail terms. Similarly, the UK’s Defamation Act 2013 provides for serious legal consequences, including damages and legal costs, for entities found guilty of publishing false statements that harm the reputation of others.

Additionally, your false accusations of spamming and harassment are completely unfounded. SpringRacks has only made a single, legitimate post regarding this issue. Any other posts are not from us, and your false accusations are further damaging our reputation.

Our owner, based in Mauritius, is fully prepared to initiate legal proceedings in multiple jurisdictions, including Turkey and the UK, to protect our brand and seek redress for the damages caused by your actions. SpringRacks is a trusted and verified hosting provider, as highly recognized by the r/minecraftserver subreddit, and we will not tolerate defamatory actions from your organization or any other third party.

Furthermore, your suggestion that we comply with your guidelines is entirely irrelevant. SpringRacks should never have been listed as a summer host in the first place. Our Terms of Service (TOS) are specifically designed to protect our interests and ensure the integrity of our business operations. Any attempt by your organization to impose external rules on our TOS is unacceptable and constitutes an overreach of your authority. Your platform does not have the right to dictate the terms under which our services are listed, especially when such listings are erroneous and damaging to our brand. It is imperative that you respect our established guidelines and cease any further attempts to control or alter our TOS.

Therefore, I demand once again that SpringRacks be immediately removed from your summer host list. This is your final opportunity to rectify this situation before we proceed with comprehensive legal action, including but not limited to filing defamation and libel suits in both Turkey and the UK.

We expect you to take this matter seriously and act without further delay. Failure to comply will result in severe legal consequences.

Sincerely,

LayTooPlant
Sys Admin
SpringRacks

**Comment by smashyalts** [comment]
weird for the sys-admin to do this, shouldnt the Legal department/lawyer do that?

**Comment by smashyalts** [comment]
another thing, the word summerhost is not in a legitimate and "trusted" dictionary, so being called a summerhost varies on the person as there isnt a set in stone definition, setup.md has CLEARLY said reasons for why springracks is on the list, and what can put a host on the list, theres no false statements (IANAL) because... Summerhost is not a actual word with a legitimate meaning and the reasons put up why your on the list
![billede](https://github.com/user-attachments/assets/ad019597-cb07-436d-adea-5276d985a061)
![billede](https://github.com/user-attachments/assets/f550b16c-5c33-42d0-8668-967cc8fcef8a)
The reason your put on the list is a valid and legitimate thing in your tos so how is that a false statement?

**Comment by smashyalts** [comment]
@LayTooPlant

**Comment by smashyalts** [comment]
Oh wait, you arent even affiliated with springracks

**Comment by TheVillainousBread** [comment]
As someone who actually is affiliated with SpringRacks, we have no records of any system administrator by the name "LayTooPlant". This threat of being sued can be happily ignored as they do not represent as in any means or are associated with us. We have had issues of our company and some of our staff being impersonated and any issues that we have must be handled by upper management than a system admin. 

Though, we find it a concern that we are label as a Summer Host and instead of going around and threatening to sue like our imposter, we would like to discuss this matter privately to ensure that our brand is not associated with such behavior or as a Summer Host. 

Best regards,
Brandon
Support/Marketing Manager of SpringRacks Hosting

**Comment by EternalTheGod** [comment]
Thanks for the reply, Brandon.
