### ISSUE TITLE
Craftlands

### ISSUE THREAD

**Issue by Nufless** [setupmd/docs#138]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Craftlands.host

### Rule Violations

Faked uptime on website
They have live updates on discord 
![image](https://github.com/user-attachments/assets/dcd31546-98b2-49b5-823c-92756b2bb743)
(2 hour downtime)

![image](https://github.com/user-attachments/assets/e4d476da-4a53-47f2-a960-61aa756ae681)
Status page on their site shows 100%... Yeah, not true

If you look through everything on the status and discord, there are other occurrences of this

**Comment by EternalTheGod** [comment]
Uptimekurma doesn't really list old uptime records, based on the date of the message in the first screenshot (discord embed) the uptime message was sent on 08/19/2024, while the issue was created on 08/30/2024. When did you take the second screenshot? Chances are it was after the incident on 08/19/2024, which if is true then the issue can be closed.

**Comment by EternalTheGod** [comment]
Closing due to the lack of a response
